export const cardData = [
  {
    image: 'https://via.placeholder.com/200x180.png?text=Frontend',
    title: 'Desenvolvedor Frontend',
    name: 'Ana Souza',
    distance: '1.5km',
    daysAgo: '2 dias',
  },
  {
    image: 'https://via.placeholder.com/200x180.png?text=Software+Engineer',
    title: 'Engenheiro de Software',
    name: 'Carlos Almeida',
    distance: '3km',
    daysAgo: '4 dias',
  },
  {
    image: 'https://via.placeholder.com/200x180.png?text=Data+Analyst',
    title: 'Analista de Dados',
    name: 'Paula Fernandes',
    distance: '5km',
    daysAgo: '1 dia',
  },
  {
    image: 'https://via.placeholder.com/200x180.png?text=UX%2FUI+Designer',
    title: 'Designer UX/UI',
    name: 'Rodrigo Ribeiro',
    distance: '2.3km',
    daysAgo: '3 dias',
  },
  {
    image: 'https://via.placeholder.com/200x180.png?text=Project+Manager',
    title: 'Gerente de Projetos',
    name: 'Fernanda Costa',
    distance: '4.7km',
    daysAgo: '5 dias',
  },
  {
    image: 'https://via.placeholder.com/200x180.png?text=Backend+Developer',
    title: 'Desenvolvedor Backend',
    name: 'Marcos Silva',
    distance: '2km',
    daysAgo: '2 dias',
  },
  {
    image: 'https://via.placeholder.com/200x180.png?text=QA+Tester',
    title: 'QA Tester',
    name: 'Juliana Melo',
    distance: '1.8km',
    daysAgo: '3 dias',
  },
  {
    image: 'https://via.placeholder.com/200x180.png?text=Product+Owner',
    title: 'Product Owner',
    name: 'Gustavo Torres',
    distance: '6km',
    daysAgo: '6 dias',
  },
  {
    image: 'https://via.placeholder.com/200x180.png?text=Scrum+Master',
    title: 'Scrum Master',
    name: 'Larissa Rocha',
    distance: '3.5km',
    daysAgo: '2 dias',
  },
  {
    image: 'https://via.placeholder.com/200x180.png?text=DevOps+Specialist',
    title: 'Especialista DevOps',
    name: 'Renato Oliveira',
    distance: '2.2km',
    daysAgo: '4 dias',
  },
  {
    image: 'https://via.placeholder.com/200x180.png?text=DevOps+Specialist',
    title: 'Especialista DevOps',
    name: 'Renato Oliveira',
    distance: '2.2km',
    daysAgo: '4 dias',
  },
  {
    image: 'https://via.placeholder.com/200x180.png?text=DevOps+Specialist',
    title: 'Especialista DevOps',
    name: 'Renato Oliveira',
    distance: '2.2km',
    daysAgo: '4 dias',
  },
]
