name: Deploy to Vercel

on:
  push:
    branches:
      - develop  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Escolha a versão do Node.js que seu projeto usa
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install

      - name: Install Vercel CLI
        run: yarn global add vercel

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: vercel --prod --confirm
