name: Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - release
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '>=18'
      
      - name: Install Yarn
        run: npm install --global yarn

      - name: Install Dependencies
        run: yarn install
        
      - name: Build Project
        run: yarn build




  deployment-production:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Deploy Project to Production
        run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }}